spring:
  profiles:
    active: development,default
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5433/openpayd
  jpa:
    open-in-view: false
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
server:
  port: 9091
  sessionTimeout: 30